import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, join } from 'node:path'
import { seedState } from '../src/store/state.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

export function generate() {
  const css = readFileSync(join(root, 'src/styles/tokens.css'), 'utf8')
  const vars = [...css.matchAll(/(--[a-z0-9-]+):\s*([^;]+);/g)]
    .map(([, name, value]) => [name, value.trim()])
  // Dedupe by CSS variable name (last declaration wins, matching CSS cascade
  // semantics) before emitting, a Swift dictionary literal with duplicate
  // keys is a runtime crash, so tokens.css ever gaining a second block for
  // the same var must not produce one.
  const deduped = new Map(vars)
  const entries = [...deduped].map(([n, v]) => `        "${n}": "${v.replaceAll('"', '\\"')}",`).join('\n')
  const tokensSwift = `// GENERATED by scripts/gen-ios.mjs, do not edit. Source: src/styles/tokens.css
enum Tokens {
    static let defaults: [String: String] = [
${entries}
    ]
}
`
  return { tokensSwift, seedJson: JSON.stringify(seedState(), null, 2) }
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  const { tokensSwift, seedJson } = generate()
  mkdirSync(join(root, 'ios/Sources/Generated'), { recursive: true })
  mkdirSync(join(root, 'ios/Resources'), { recursive: true })
  writeFileSync(join(root, 'ios/Sources/Generated/Tokens.swift'), tokensSwift)
  writeFileSync(join(root, 'ios/Resources/seed.json'), seedJson)
  console.log('[gen-ios] wrote Tokens.swift and seed.json')
}
